export enum ServiceType {
  CATERING = "CATERING",
  WEDDING_PLANNING = "WEDDING_PLANNING",
  VENUE = "VENUE",
  PHOTOGRAPHY = "PHOTOGRAPHY",
  MUSIC = "MUSIC",
  DECORATION = "DECORATION",
  OTHER = "OTHER"
} 